//
//  RecipesLibrary.swift
//
//  Swift facing layer over the Kotlin `SharedRecipes` framework.
//
//  Kotlin/Native exports suspend functions to Objective-C as completion-handler
//  methods, so this file converts each call into a Swift `async` function and
//  replaces the `RecipesResult` envelope with a thrown Swift error. The Kotlin
//  API itself stays unchanged so it remains usable from Android, JVM and JS.
//
//  Concurrency diagnostics are relaxed for this file: headers generated by
//  Kotlin/Native cannot carry Sendable annotations, so every completion handler
//  they declare is implicitly non-Sendable.
//

@preconcurrency import Foundation
import SharedRecipes

// MARK: - Errors

/// Error thrown by the Swift wrappers.
public enum RecipesError: Error, LocalizedError {
    /// The API call failed. Inspect ``failure`` for the reason.
    case api(RecipesFailure)
    /// The framework returned neither a result nor an error.
    case missingResult

    public var errorDescription: String? {
        switch self {
        case .api(let failure):
            return failure.failureDescription
        case .missingResult:
            return "The recipes library returned no result."
        }
    }

    /// Machine readable kind, one of the `RecipesFailureKind` constants.
    public var kind: String {
        switch self {
        case .api(let failure): return failure.kind
        case .missingResult: return RecipesFailureKind.shared.Unexpected
        }
    }
}

public extension RecipesFailure {
    /// Human readable description, mirroring Kotlin's `Throwable.message`.
    var failureDescription: String { message ?? kind }

    /// `true` when retrying could succeed, matching the library's own policy.
    var isTransient: Bool {
        if let http = self as? RecipesHttpFailure {
            return http.isServerError || http.isRateLimited
        }
        let kind = RecipesFailureKind.shared
        return self.kind == kind.Network || self.kind == kind.Timeout
    }
}

// MARK: - Bridging

/// Runs one Kotlin completion-handler call as a Swift `async` call.
@MainActor
@discardableResult
func recipesBridge<T>(
    _ body: (@escaping @Sendable (RecipesResult<T>?, Error?) -> Void) -> Void
) async throws -> T {
    try await withCheckedThrowingContinuation { continuation in
        body { result, error in
            if let error {
                continuation.resume(throwing: error)
                return
            }
            guard let result else {
                continuation.resume(throwing: RecipesError.missingResult)
                return
            }
            // `failureOrNull()` is the reliable discriminator: Objective-C
            // generics erase the concrete `RecipesResult` subclass.
            if let failure = result.failureOrNull() {
                continuation.resume(throwing: RecipesError.api(failure))
                return
            }
            if let success = result as? RecipesResultSuccess<T>, let value = success.value {
                continuation.resume(returning: value)
            } else {
                continuation.resume(throwing: RecipesError.missingResult)
            }
        }
    }
}

// MARK: - Page

/// A page of recipes; shorthand for `Page<Recipe>`.
public typealias RecipesPage = Page<Recipe>

public extension Page where T == Recipe {
    /// `true` when more recipes are available on the server.
    var canLoadMore: Bool { hasMore }

    /// Zero-based index of this page.
    var index: Int { Int(pageIndex) }
}

// MARK: - Repository

@MainActor
public extension RecipesRepository {

    /// Creates a repository that talks to DummyJSON.
    ///
    /// `nonisolated` so it can be used from default arguments and previews.
    nonisolated static func live() -> RecipesRepository { RecipesRepository.companion.create() }

    /// Creates a repository for a custom base URL.
    nonisolated static func live(baseURL: String) -> RecipesRepository {
        RecipesRepository.companion.create(baseUrl: baseURL)
    }

    // MARK: Reading

    /// Returns one page of recipes.
    func recipes(query: RecipesQuery) async throws -> RecipesPage {
        try await recipesBridge { completion in
            self.getRecipes(query: query, completionHandler: completion)
        }
    }

    /// Returns the first page of recipes.
    func recipes(limit: Int32 = 30, skip: Int32 = 0) async throws -> RecipesPage {
        try await recipesBridge { completion in
            self.getRecipes(limit: limit, skip: skip, completionHandler: completion)
        }
    }

    /// Returns a single recipe by id.
    func recipe(id: Int32) async throws -> Recipe {
        try await recipesBridge { completion in
            self.getRecipe(id: id, completionHandler: completion)
        }
    }

    /// Searches recipes by name.
    func search(_ text: String, query: RecipesQuery) async throws -> RecipesPage {
        try await recipesBridge { completion in
            self.searchRecipes(query: text, page: query, completionHandler: completion)
        }
    }

    /// Returns recipes carrying `tag`.
    func recipes(tag: String, query: RecipesQuery) async throws -> RecipesPage {
        try await recipesBridge { completion in
            self.getRecipesByTag(tag: tag, page: query, completionHandler: completion)
        }
    }

    /// Returns recipes for a meal type such as `"Dinner"`.
    func recipes(mealType: String, query: RecipesQuery) async throws -> RecipesPage {
        try await recipesBridge { completion in
            self.getRecipesByMealType(mealType: mealType, page: query, completionHandler: completion)
        }
    }

    /// Returns recipes for a difficulty, filtered on the client.
    func recipes(difficulty: String, query: RecipesQuery) async throws -> RecipesPage {
        try await recipesBridge { completion in
            self.getRecipesByDifficulty(difficulty: difficulty, query: query, completionHandler: completion)
        }
    }

    /// Returns every tag known to the API.
    func tags() async throws -> [String] {
        let array: NSArray = try await recipesBridge { completion in
            self.getTags(completionHandler: completion)
        }
        return array as? [String] ?? []
    }

    /// Returns every distinct meal type in the dataset.
    func mealTypes(maxRecipes: Int32 = 1000) async throws -> [String] {
        let array: NSArray = try await recipesBridge { completion in
            self.getMealTypes(maxRecipes: maxRecipes, completionHandler: completion)
        }
        return array as? [String] ?? []
    }

    /// Returns every recipe, following pagination until the dataset is drained.
    func allRecipes(pageSize: Int32 = 30, maxRecipes: Int32 = 1000) async throws -> [Recipe] {
        let array: NSArray = try await recipesBridge { completion in
            self.getAllRecipes(pageSize: pageSize, maxRecipes: maxRecipes, completionHandler: completion)
        }
        return array as? [Recipe] ?? []
    }

    // MARK: Writing

    /// Simulates `POST /recipes/add`.
    func add(recipe: NewRecipe) async throws -> Recipe {
        try await recipesBridge { completion in
            self.addRecipe(recipe: recipe, completionHandler: completion)
        }
    }

    /// Simulates `PUT /recipes/{id}`.
    func update(id: Int32, update: RecipeUpdate) async throws -> Recipe {
        try await recipesBridge { completion in
            self.updateRecipe(id: id, update: update, completionHandler: completion)
        }
    }

    /// Simulates `PATCH /recipes/{id}`.
    func patch(id: Int32, update: RecipeUpdate) async throws -> Recipe {
        try await recipesBridge { completion in
            self.patchRecipe(id: id, update: update, completionHandler: completion)
        }
    }

    /// Simulates `DELETE /recipes/{id}`.
    func delete(id: Int32) async throws -> DeletedRecipe {
        try await recipesBridge { completion in
            self.deleteRecipe(id: id, completionHandler: completion)
        }
    }

    // MARK: Lifecycle

    /// Releases the underlying HTTP client.
    func closeRepository() async throws {
        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
            self.close(completionHandler: { error in
                if let error {
                    continuation.resume(throwing: error)
                } else {
                    continuation.resume()
                }
            })
        }
    }
}

// MARK: - Query helpers

@MainActor
public extension RecipesQuery {

    /// A query for a single page, optionally sorted.
    ///
    /// `RecipesQuery`'s designated initializer takes every parameter, and Kotlin
    /// default arguments are not exported to Swift, so this covers the common
    /// cases.
    static func page(
        limit: Int32 = RecipesApi.shared.DefaultLimit,
        skip: Int32 = 0,
        sortBy: String? = nil,
        order: String? = nil
    ) -> RecipesQuery {
        RecipesQuery(
            limit: limit,
            skip: skip,
            sortBy: sortBy,
            order: order,
            select: []
        )
    }

    /// The page that follows `page`, or `nil` when it was the last one.
    static func following(_ page: RecipesPage) -> RecipesQuery? {
        guard let next = page.nextSkip() else { return nil }
        return .page(limit: page.limit, skip: next.int32Value)
    }}
