//
//  RecipesSwift.swift
//
//  The Kotlin/Native framework exports `RecipesRepository` with completion
//  handlers, because suspend functions are bridged to Objective-C that way.
//  This file adds thin `async`/`await` wrappers so the library feels native in
//  Swift, and re-exports the Kotlin error type under a Swift name.
//
//  Add this file to your app target together with the `SharedRecipes` binary
//  target (the Swift Package already ships it).
//

// Concurrency diagnostics are relaxed for this file: the headers generated by
// Kotlin/Native cannot carry Sendable annotations, so every completion handler
// they declare is implicitly non-Sendable.
@preconcurrency import Foundation
import SharedRecipes

/// Error thrown by the Swift `async` wrappers.
public enum RecipesError: Error {
    /// The API call failed; inspect ``failure`` for the reason.
    case api(RecipesFailure)
    /// The framework returned neither a result nor an error.
    case missingResult
}

extension RecipesFailure {
    /// Human readable description, mirroring `Throwable.message`.
    public var localizedDescriptionText: String { message ?? kind }
}

/// Bridges one Kotlin completion-handler call into an `async` call.
@MainActor
@discardableResult
private func recipesBridge<T>(
    _ body: (@escaping @Sendable (RecipesResult<T>?, Error?) -> Void) -> Void
) async throws -> T {
    try await withCheckedThrowingContinuation { continuation in
        body { result, error in
            if let error {
                continuation.resume(throwing: error)
                return
            }
            guard let result else {
                continuation.resume(throwing: RecipesError.missingResult)
                return
            }
            if let failure = result.failureOrNull() {
                continuation.resume(throwing: RecipesError.api(failure))
                return
            }
            if let success = result as? RecipesResultSuccess<T>, let value = success.value {
                continuation.resume(returning: value)
            } else {
                continuation.resume(throwing: RecipesError.missingResult)
            }
        }
    }
}

@MainActor
public extension RecipesRepository {

    /// Creates a repository that talks to DummyJSON.
    static func live() -> RecipesRepository { RecipesRepository.companion.create() }

    /// Returns one page of recipes.
    func recipes(query: RecipesQuery) async throws -> Page<Recipe> {
        try await recipesBridge { completion in
            self.getRecipes(query: query, completionHandler: completion)
        }
    }

    /// Returns the first page of recipes.
    func recipes(limit: Int32 = 30, skip: Int32 = 0) async throws -> Page<Recipe> {
        try await recipesBridge { completion in
            self.getRecipes(limit: limit, skip: skip, completionHandler: completion)
        }
    }

    /// Returns a single recipe by id.
    func recipe(id: Int32) async throws -> Recipe {
        try await recipesBridge { completion in
            self.getRecipe(id: id, completionHandler: completion)
        }
    }

    /// Searches recipes by name.
    func search(_ text: String, query: RecipesQuery) async throws -> Page<Recipe> {
        try await recipesBridge { completion in
            self.searchRecipes(query: text, page: query, completionHandler: completion)
        }
    }

    /// Returns recipes carrying `tag`.
    func recipes(tag: String, query: RecipesQuery) async throws -> Page<Recipe> {
        try await recipesBridge { completion in
            self.getRecipesByTag(tag: tag, page: query, completionHandler: completion)
        }
    }

    /// Returns recipes for a meal type such as `"Dinner"`.
    func recipes(mealType: String, query: RecipesQuery) async throws -> Page<Recipe> {
        try await recipesBridge { completion in
            self.getRecipesByMealType(mealType: mealType, page: query, completionHandler: completion)
        }
    }

    /// Returns every tag known to the API.
    func tags() async throws -> [String] {
        let array: NSArray = try await recipesBridge { completion in
            self.getTags(completionHandler: completion)
        }
        return array as? [String] ?? []
    }

    /// Returns every recipe, following pagination until the dataset is drained.
    func allRecipes(pageSize: Int32 = 30, maxRecipes: Int32 = 1000) async throws -> [Recipe] {
        let array: NSArray = try await recipesBridge { completion in
            self.getAllRecipes(pageSize: pageSize, maxRecipes: maxRecipes, completionHandler: completion)
        }
        return array as? [Recipe] ?? []
    }

    /// Simulates `POST /recipes/add` and returns the created recipe.
    func add(recipe: NewRecipe) async throws -> Recipe {
        try await recipesBridge { completion in
            self.addRecipe(recipe: recipe, completionHandler: completion)
        }
    }

    /// Simulates `PUT /recipes/{id}`.
    func update(id: Int32, update: RecipeUpdate) async throws -> Recipe {
        try await recipesBridge { completion in
            self.updateRecipe(id: id, update: update, completionHandler: completion)
        }
    }

    /// Simulates `PATCH /recipes/{id}`.
    func patch(id: Int32, update: RecipeUpdate) async throws -> Recipe {
        try await recipesBridge { completion in
            self.patchRecipe(id: id, update: update, completionHandler: completion)
        }
    }

    /// Simulates `DELETE /recipes/{id}`.
    func delete(id: Int32) async throws -> DeletedRecipe {
        try await recipesBridge { completion in
            self.deleteRecipe(id: id, completionHandler: completion)
        }
    }

    /// Releases the underlying HTTP client.
    func closeRepository() async throws {
        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
            self.close(completionHandler: { error in
                if let error {
                    continuation.resume(throwing: error)
                } else {
                    continuation.resume()
                }
            })
        }
    }
}
